# Publish to Maven Central
#
# Instructions from https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c

name: publish

on:
  repository_dispatch:
    types: manual-publish
# once all is working, also trigger when release is created
#  release:
#    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: install-secret-key
        name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.SEER_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Build with Gradle
        run: ./gradlew publish closeAndReleaseRepository
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.SEER_GPG_KEYID }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.SEER_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.secretKeyRingFile: ${{ secrets.SEER_GPG_SECRET_KEYRING_FILE }}
